### ISSUE TITLE
Root url with rewritten storeview code only works when ending with a slash

### ISSUE THREAD

**Issue by TimQSO** [experius/Magento2-Module-Multiple-Website-Store-Code-Url#5]
Magento 2.3.3
Nginx 1.17
PHP 7.3

english_en as storeview code is rewritten in de URL as /en/, for example:

https://www.mywebsite.com/en/ 

And this shows the English storeview, however, when we remove the last slash, the storeview code is not recognized anymore, thus:

https://www.mywebsite.com/en

Will use the fallback to the default storeview and in our case this is Dutch. The homepage shows in Dutch without the last slash and all the links on the homepage refer to /nl/ pages.

The default Magento behaviour recognizes the storeview code with and without a slash on the end.

**Comment by lewisvoncken** [comment]
@GuiltyNL can you please confirm that this is solved in the release 2.1.0

**Comment by TimQSO** [comment]
Hi @lewisvoncken I had to use another solution because of the issues I mentioned. So at this point I'm not using the module anymore, sorry.

**Comment by Alex7Lem** [comment]
> Hi @lewisvoncken I had to use another solution because of the issues I mentioned. So at this point I'm not using the module anymore, sorry.

Please tell me which module are you using instead of this buggy?

**Comment by TimQSO** [comment]
I'm using a solution with sub folders and a simple nginx config to support it.

**Comment by Alex7Lem** [comment]
> I'm using a solution with sub folders and a simple nginx config to support it.

Cool
I use nginx too
Please tell me where can I find out more about this solution?

**Comment by TimQSO** [comment]
@Alex7Lem Sorry, I've missed your reply. Look here:

https://community.magento.com/t5/Magento-2-x-Admin-Configuration/Magento-2-Multi-Site-with-Subdirectories-Setup/td-p/121686

And here:

https://support.hypernode.com/en/hypernode/nginx/how-to-configure-run-codes-and-run-types-in-nginx#Configuring_a_location_block_to_instruct_Nginx_to_serve_the_correct_subdirectory

We use the solution with symlinking the subfolders to the root. Works well.
