### ISSUE TITLE
Third party issue: cache warmers

### ISSUE THREAD

**Issue by TimQSO** [experius/Magento2-Module-Multiple-Website-Store-Code-Url#7]
Third party cache warmers that construct urls from the database are having issues with the rewritten storefront urls.

The warmer we use (from Potato Commerce) constructs, just like the sitemap generation, the url with the full store_code including the website_code prefix. Resulting in a non working cache warmer.

As a workaround I use a scheduled Mysql EVENT to replace the full store_code in the url with the stripped store_code in the cache warmer queue. 

I'm not sure if you are able to change your logic to prevent issues like this. But I thought it is good to let you know the issue.

**Comment by lewisvoncken** [comment]
@GuiltyNL this is resolved in the latest version 2.1.0
